# Docker Compose
# https://docs.docker.com/compose/

version: '3.6'
services:
  # PostgreSQL database.
  db:
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=equipindustry-visanet
    volumes:
      - db:/var/lib/postgresql/data # Using the declared volume.
      - .:/usr/src

  app:
    image: equipindustry-visanet-app-dev
    environment: &environment
      - EQUIP_CORE_APP_ENV=dev
      - EQUIP_CORE_DATABASE_NAME=equipindustry-visanet
      - EQUIP_CORE_DATABASE_USER=postgres
      - EQUIP_CORE_DATABASE_PASS=postgres
      - EQUIP_CORE_DATABASE_HOST=db
      - EQUIP_CORE_DATABASE_PORT=5432
      - EQUIP_CORE_DATABASE_URL=postgres://postgres:postgres@db:5432/equipindustry-visanet?sslmode=disable
    build:
      args:
        stage: dev
    volumes:
      - .:/usr/src
    env_file:
      - .env
    depends_on:
      - db

  check:
    image: equipindustry-visanet-check-dev
    environment: *environment
    build:
      context: .
      dockerfile: provision/docker/check/Dockerfile
      args:
        stage: dev
    volumes:
      - .:/usr/src
    env_file:
      - .env

volumes:
  db:
